# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
